# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

logo: assets/jeanlescure-logo.svg
title: ''
author: Jean M. Lescure

exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints", "**node_modules"]
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/jeanlescure/typescript-jupyter-book-template  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  extra_footer: |
    <p>
      © Copyright 2020-<script>document.write((new Date()).getFullYear())</script>
    </p>

launch_buttons:
  notebook_interface: classic  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: ''  # The URL of the BinderHub (e.g., https://mybinder.org)
  jupyterhub_url: ''  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  thebe: false  # Add a thebe button to pages (requires the repository to run on Binder)
  colab_url: ''

sphinx:
  extra_extensions:
    - sphinxcontrib.apa
  config:
    bibtex_reference_style: apastyle
    bibtex_default_style: apa
    language: en
    html_show_copyright: false
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js