# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

logo: assets/jeanlescure-logo.svg
title: ''
author: Jean M. Lescure

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/jeanlescure/book  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  extra_footer: |
    <p>
      © Copyright 2020-<script>document.write((new Date()).getFullYear())</script>
    </p>

sphinx:
  extra_extensions:
    - sphinxcontrib.apa
  config:
    bibtex_reference_style: apastyle
    bibtex_default_style: apa
    language: en
    html_show_copyright: false